language: go

go:
- master

go_import_path: github.com/narrowizard/nirvana-cms

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=narrowizard/nirvana-cms
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
