language: go

go:
- master

go_import_path: github.com/narrowizard/nirvana-cms

env:
  global:
    - secure: "HZ7AXO8TAHsoZAhvW7VTIeOt2gk6LURoJGolPsaAdIA5p9CH0dMCAp82BwuIUo/Ekdx94MA48wiAYz7irOqOQZGclxdf1Ktffu25onyB8bqTpXFHVsT74s+8vTEG3Ia6w2sxoxJo9zq59EQ1UlLlut5zDu0L1p67249Pyg8E2MHQMxBqO2AQUyXVAVONnuxsPgPC2DqYfC84Nb23oH9Ba91wZS+g8cn5keKWnNM3b72ke5qSfiOxDzxC+jj9uBEfqEBMam7vhHgwUO1yNAvuWh/aiWehJWzgUHpBgVw5oHC+2nsdzYIileDFk/C240aVuDZCSXicvKG/xmvYYAsb4gMnQYPw2yzJz2iteCXtvsXRaOTFwpeJMp1kSV4NPLzQidH++ISOcrJFbZOzz3+xPV3PMNfX/Gzy90Pi+yVv0siRZZPuVvEXBxe6Mp5cqD08YiddaiienOwSFsuFkyehgt1t2a7p0V7fj6fMG5Z+CJ6Vo2bSnWbiseyMD2ET6cB30SA6ZPpoxU3FHcLS0Twg2z5B13udR1+ux5riwnHhgSvQTcmpKixvGVVotliHBDAxD+4/6TVEQcSO7fIvoif+O3eqaYNWkXIE/JZlialv6tCr9kQ0ceZ7XwLYzuxv4fE/ICozfjAu697JkDC6fGdTHf8sRLnrvTYpH6mBfVnLBFo="
    - secure: "6eQgwe23Lh43d+g/Q8ZV2gtOBZWF2P55xAitjPZMf7TcbaQ33OrM2HIyuICoRxgEO3ggQk7xtfmbMIt8/TIkM6Vm4QrA1dBpFHQ2P2fnW161bB3v8rUN1hzz+Z2poGOz5Qxb3a6h8mlL7Sx+adC/3kJPsT+vfI00zpYj+zcvHdMKSwZGuMRS2XqX30BxA8v7eSgflbCGDuDhdOQWqTMnyyHoB9Uemuu1nCnGBCYMgxCWArRb94Nj2nzhOQF9Cex6tAUZ2yvfaKm6+9Ot8Ds/Lei5naPb9NGu0iOUtUh2rJ/NPO5hw09D/WbB6g9GGO82jBvxcK9Z+sRQ4eO4Kw9eOPgHhnLlppFQiWbAvQNGXWASgo0cOMbG6JWc2TFdvyVfAqaQg7yuiAaR30GY/rF/LLHDQhL+q3COHjYwxx1LBEt2S4wrg2wmJRKBUl5xhT6XaC+2hCbRH9hjx8TxauLq4xO97cm+5rqupVLzBtznLLrkPsIyYtvbINlUJIY0Rcum4wjYMzA4jU164AmguMWYadM/TKJEidROpecNEnmO+YFzykm+F6BSwQrIeEuJW90Mcae5pzCgOdY4tNBWtH8DFXjFfBgfFg135jUluvZUbJN3ditnFqfoXjdoX7azJq3zRn+TewosYWKyfdJlsCqoSInuAU2Q/9z1HsLmNOfjJwE="
    - COMMIT=${TRAVIS_COMMIT::8}
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=narrowizard/nirvana-cms
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
